LIBRARY = Analyzers
OBJDIR = obj
DEPDIR = $(OBJDIR)/dep
SRCDIR = src
INCDIR = include
ADDITIONAL_ROOTMAPLIBRARY = -rml libAnalyzerTools.so -rml libGEScaleSyst.so -rml libDataFormats.so -rml libTree.so

include $(SKFlat_WD)/makefile.common

INCLUDES += -I$(SKFlat_WD)/DataFormats/include/
INCLUDES += -I$(SKFlat_WD)/AnalyzerTools/include/
INCLUDES += -I$(SKFlat_WD)/external/GEScaleSyst/
#INCLUDES += -I/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/lhapdf/6.2.1-fmblme/include/
#INCLUDES += -I/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-numpy/1.14.1-gnimlf2/lib/python2.7/site-packages/numpy/core/include/
#INCLUDES += -I/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-numpy/1.16.2-pafccj/lib/python2.7/site-packages/numpy/core/include/
INCLUDES += -I/cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/py2-numpy/1.16.6/lib/python2.7/site-packages/numpy/core/include/
#INCLUDES += -I/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07/lib/
